- name: loops
  hosts: local
  connection: local
  tasks:
  - name: loops_names
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - redis
    - zip