- name: shell_vs_command
  hosts: local
  connection: local
  tasks:
  - name: shell_exec
    ansible.builtin.shell: "ls -lrt > /tmp/output.txt"
    register: command_result

  - name: print_shell_result
    ansible.builtin.debug:
      msg: "{{ command_result }}"

  - name: command_exec
    ansible.builtin.command: "ls -lrt"
    register: command_result

  - name: print_command_result
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.debug: 
      msg: "{{ command_result }}"
    