- name: prompt_vars
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: enter your username
    private: false
  
  - name: password
    prompt: enter your password
    private: true

  tasks:
  - name: printing the info with play_vars
    ansible.builtin.debug:
      msg: "hello username: {{ username }} sir, password: {{ password }}"
      
  