#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]
then
    echo " please run with root access"
    exit 1
else
    echo " you are running with root access"
fi

dnf list installed mysql

if [ $? -eq 0 ]
then
    echo "mysql installed already success"
else
    echo "mysql not installed...now installing"

    dnf install mysql -y

    if [ $? -eq 0 ]
    then
        echo "mysql installed correctly"
    else    
        echo "mysql did not installed correctly"
        exit 1
    fi
fi